services:
  - type: cron
    name: laudus-backfill-ene-sep
    env: python
    plan: free
    region: oregon
    schedule: "0 2 * * *"  # 23:00 Chile (UTC-3) = 02:00 UTC
    repo: https://github.com/victor-hernandez-kirovich/laudus-api
    branch: main
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r scripts/requirements.txt
    startCommand: python scripts/fetch_balancesheet_backfill.py
    
    envVars:
      # Configuración de la API de Laudus
      - key: LAUDUS_API_URL
        value: https://api.laudus.cl
      
      - key: LAUDUS_USERNAME
        value: API
      
      # ⚠️ CONFIGURAR EN RENDER UI (son secretos):
      - key: LAUDUS_PASSWORD
        sync: false
      
      - key: LAUDUS_COMPANY_VAT
        sync: false
      
      # MongoDB Configuration
      - key: MONGODB_URI
        sync: false
      
      - key: MONGODB_DATABASE
        value: laudus_data
      
      # Backfill Configuration
      - key: BACKFILL_START_DATE
        value: "2025-01-01"
      
      - key: BACKFILL_END_DATE
        value: "2025-09-30"
      
      - key: BACKFILL_MODE
        value: monthly
      
      - key: MAX_DATES_PER_RUN
        value: "31"
      
      - key: PYTHONUNBUFFERED
        value: "1"
